# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file into the container at /usr/src/app
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your app's source code from your host to your image filesystem.
COPY spotify_reco ./spotify_reco

# The command to run when the container starts
CMD ["uvicorn", "spotify_reco.api.main:app", "--host", "0.0.0.0", "--port", "80"]
